version: "3"

services:

    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
        working_dir: /var/www/

    angular:
        build: ./angular/
        container_name: angular
        volumes:
            - ../frontend:/mnt/frontend/
        working_dir: /mnt/frontend/
        command: sh -c "npm install && ng serve"
        ports:
            - "4200:4200"