version: "3"

services:

    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            
    rails:
        build: ./rails/
        container_name: rails
        user: $user
        ports:
            - "3000:3000"
        volumes: 
            - ../:/app
        links:
            - mysql
        working_dir: /app
        tty: true
        # command: sh -c "bundle install && rails s -p 3000 -b '0.0.0.0'"