version: "3.9"

services:

    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf

    rails:
        build: ../app
        user: $user
        container_name: rails
        # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - ../app:/myapp
        ports:
            - "3000:3000"
        depends_on:
            - mysql